# Runs shell script runs meTypeset through a corpus of documents, checks to make sure that they match
# with the JATS Green XML standard, and then runs a Robot Test Framework (meTypeset), to ensure that
# the converted meTypeset'd document produces a document that matches with a corresponding sample 
# in the corpus. 


# Clears previous work. 

rm -rf /var/local/meTypesetTests/tests/testOutput
rm -rf /var/local/meTypesetTests/tests/error
mkdir  /var/local/meTypesetTests/tests/error
mkdir  /var/local/meTypesetTests/tests/testOutput

cd /var/local/meTypesetTests/testingDocuments/OpenMedDocx

# Runs meTypeset through every .docx in the corpus. Removes all results if it takes longer than 5 minutes 
# to complete the conversion process on an individual document. 

for f in *; do 
	declare -i RETURNVAL=0
	RETURNVAL= timeout 5m  python /var/www/public/parsingdev/meTypeset/bin/meTypeset.py docx "$f" /var/local/meTypesetTests/tests/testOutput/"$f" -d --nogit
	if [ $RETURNVAL -eq 124 ]; then
		rm -rf /var/local/meTypesetTests/tests/testOutput/"$f"	
	fi
done

cd /var/local/meTypesetTests/tests/testOutput

# Runs xmllint through every converted .docx file to see if it mactches the JATS Green XML standard. 

for dir in *; do 
	declare -i RETURNVAL=0
	returnval= timeout  5m xmllint --dtdvalid http://jats.nlm.nih.gov/archiving/1.1d3/JATS-archivearticle1.dtd "$dir"/nlm/out.xml 2> /var/local/meTypesetTests/tests/error/"$dir" 
	if [ $RETURNVAL -eq 124 -a -a /var/local/meTypesetTests/tests/error/"$dir" ]; then
		rm -rf /var/local/meTypesetTests/tests/error/"$dir"
	fi
done

cd /var/local/meTypesetTests/tests

# Runs the Robot Framework Test. 

pybot testForSuccessfulConversion.txt

# Transfers output generated by the Robot Framework test to a publicly available website. 

yes | cp -i			log.html          /var/www/public/parsingdev/robot/Corpus
yes | cp -i 		output.xml       /var/www/public/parsingdev/robot/Corpus
yes | cp -i 		report.html		/var/www/public/parsingdev/robot/Corpus
